services:
  dating-app-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    container_name: "dating-app-service"
    command: ["./dating-app-service"]
    working_dir: /app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
